### ISSUE TITLE
Move recipes into a configuration file

### ISSUE THREAD

**Issue by bootzin** [Lemon-Juiced/LiteExchange#1]
May I suggest moving recipes into a configuration file to be saved in the config folder of the minecraft instance? That would make it easier for others to expand/change recipes to better fit their needs

**Comment by Lemon-Juiced** [comment]
No plans to do this. If recipes need be changed or altered mods such as CraftTweaker and KubeJS exist and datapacks do as well. I'm also fairly certain you can't place recipes into the config folder of a Minecraft instance because the game won't look there when initialzing recipes.

**Comment by Lemon-Juiced** [comment]
Let me add this, if you know how to do it I wouldn't be opposed, I've just never seen it done and have no reference to try to accomplish that.
